import Head from 'next/head'
import Logins from '@/components/login/login'
export default function Login() {
    return (
        <div>
            <Head>
                <title>Login in to Twitter / Twitter</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Logins />
        </div>
    )
}
