import Regsiters from 'components/register/register'
import Head from 'next/head'
export default function Register() {
  return (
    <div>
      <Head>
        <title>Register in to Twitter / Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Regsiters/>
    </div>
  )
}
