import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import PostDetails from "components/feeddetail/details";

export default function UserProfile() {
  const router = useRouter();
  console.log(router.query.username);
  return (
    <div>
      <Head>
        <title>Kelvin Naughton on 90% tried coding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostDetails />
    </div>
  );
}
