import Message from 'components/messages/message'
import Head from 'next/head'
export default function Messages() {
  return (
    <div>
      <Head>
        <title>Message \ Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Message />
    </div>
  )
}
