import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Profile from "@/components/profile/profile";

export default function UserProfile() {
  const router = useRouter();
  // console.log(router.query.username);
  return (
    <div>
      <Head>
        <title>Edidie tried coding</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Profile />
    </div>
  );
}
