import Head from 'next/head'
import '@/styles/Home.module.css'
import HomeIndex from '@/components/home/Home'
import Connect from '@/components/connect/connect'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Connect / Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <HomeIndex /> */}
      <Connect/>
    </div>
  )
}
